### PR TITLE
Update AccountRestAPIHandlerTest

### PR DESCRIPTION
**Pull request by AakarshanS09**
Changes the test class according to the naming convention

### CODE REVIEW

**Comment by AakarshanS09** [comment]
Please review the code and see any changes need to be done and merge the pull request

**Review by Rajasundhar-95 — CHANGES_REQUESTED** [review]
Please go through one more time

**Comment by AakarshanS09** [comment]
Yeah I have gone through the codes another time

**Review by Rajasundhar-95 — APPROVED** [review]
Yeah the changes has been approved

**Pull request merged**
